version: '3'
services:
  next-app:
    image : jaeyun1650/marrymo_fe
    container_name: next-app
    ports:
      - 3000:3000
    networks:
      - marrymo_net

networks:
  marrymo_net:
    external: true